import "~/styles/globals.css";

import { type Metadata } from "next";
import { Red_Hat_Display } from "next/font/google";
import { GeistSans } from "geist/font/sans";

import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
config.autoAddCss = false;

export const metadata: Metadata = {
  title: "yurUI",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const RedHatDisplay = Red_Hat_Display({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body className="bg-gradient-linear h-screen w-screen text-white">
        {children}
      </body>
    </html>
  );
}
